server:
  port: 8082

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: path_route
          uri: http://localhost:8000
          order: 0
          predicates:
            - Path=/foo/**
          filters:
            - StripPrefix=1


hystrix.command.fallbackcmd.execution.isolation.thread.timeoutInMilliseconds: 5000
