server:
  port: 8082

spring:
  application:
    name: gateway
  redis:
      host: 127.0.0.1
      port: 6379
  cloud:
    gateway:
      routes:
        - id: path_route
          uri: http://localhost:8000
          order: 0
          predicates:
            - Path=/foo/**
          filters:
            - StripPrefix=1
            - name: RequestRateLiteimr
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                key-resolver: "#{@ipKeyResolver}"

hystrix.command.fallbackcmd.execution.isolation.thread.timeoutInMilliseconds: 5000
